### ISSUE TITLE
Ugly Mode!

### ISSUE THREAD

**Issue by damteenagers** [Rinnegatamante/vitaQuake#20]
Implement this please. It gives the needed fps boost for extremists.
In the console if you type r_drawflat 1 and r_fullbright 1 you can near 60 fps at native resolution at the cost of visuals.

**Comment by Ch0wW** [comment]
r_fullbright does not improve FPS that much, maybe 2 or 3 at best, but can improve a bit visibility, especially on multiplayer. I'm okay to add this option in the menu.

However, I don't really support r_drawflat, since it was more of a debugging tool than anything else. That CVAR has been removed already in a commit I was about to send, and would confuse almost everyone.

FYI, VSync has recently been togglable, making a lot of zones to 60FPS almost everywhere, 45/50 to the rest.

**Comment by Rinnegatamante** [comment]
Ch0wW: not at native resolution <.<

**Comment by Ch0wW** [comment]
For FPS extremists, they would play at the lowest resolution available, so it's not that much of a trouble.

However, the moment we'll be able to HW-render the game, it'll be another story.
