### ISSUE TITLE
System crash: An error has occured. The PS vita system will be powered off

### ISSUE THREAD

**Issue by Count-Duckula-AU** [Rinnegatamante/vitaQuake#35]
With vitaQuake v2.6 I am having fairly regular crashes to a black screen with the message 'An error has occurred. The PS vita system will be powered off'.

I have had the issue on both my vita 2000 with sd2vita and 200gb microsd, and my pstv with official sony 32GB mem card.

It occurs after 5-10 minutes of playing, the most recent occurrence was after I started a new game, normal difficulty, first world. Part way through the second level while shooting an enemy the system crashed.

I had played a few hours of v2.5 with no crashes, just the inability to see underwater which is now fixed. 
I'm using the same ID1 folder (from steam) as I did with previous versions of vitaquake.
Uninstalling vitaquake then reinstalling v2.6 did not resolve the issue.

Crash dumps from vita2000: https://mega.nz/#F!xtdUALJb!a0SpUy18W7ndIBWbrg0T_w
The two 'GPUCRASH' files are from when this has occurred. 
The other 77-78KB crash dumps in that link are from starting up V2.6 with the official quake expansions being present in ux0:data/quake which causes an application crash (different issue).

Crash dump from PSTV: https://mega.nz/#!451zQS6K!B-fYZo8J3I2LIxXyJ6dFqzOG011odlJh_Apyab3sOyY

**Comment by Rinnegatamante** [comment]
I'm quite sure this is caused by animation interpolation sometimes failing to correctly interpolate two frames for some entities.
Try to disable this feature from your config file: https://github.com/Rinnegatamante/vitaQuake/wiki/List-of-all-available-Quake-config-settings-in-vitaQuake
r_interpolate_model_animation + r_interpolate_model_transform and let me know if the crashes stop to occur.

**Comment by Count-Duckula-AU** [comment]
Thanks for investigating :)

With those two settings (https://pastebin.com/qYqve4A4) it didn't crash in the place that it normally would, I was able to play through another 2 levels.  :)
I'll play through the same part a few more times to confirm.

Fairly reproducible crash (without interpolation disabled):
https://i.imgur.com/XAEp5iS.jpg
Start a new game normal difficulty world 1, play through level 2 to the point where you enter (from the other side of) that 'secret' door, shoot one of the enemies and it crashes a good % of the time.
I'm not sure if it's related at all, but just before getting to that secret door, as you move from underwater to above water, you can see the enemies through the level geometry for a second.

If I create a save just before that point and load it, it didn't crash :(

With interpolation disabled, the sound did start to stutter/crackle shortly after the point the game previously crashed. It persisted into the next level but didn't prevent me playing.
I noticed that https://mega.nz/#!c0UFzL7K!1aZV8_ZoNXgKf659PxfooKC6wP44ePeZpudQxdBxuuQ (which mentions 'audio thread') was created but I'm not positive if that occurred when the stuttering started or when I quit vitaquake.

**Comment by Rinnegatamante** [comment]
Are all those crashes performed with animation interpolation enabled?
I started noticing these crashes when enabling it. (Sometimes you can read from quake console something about bad frame when animation interpolation is enabled. I suspect it tries to draw some incoherent frame state resulting in a crash in sceGxm.)

**Comment by Count-Duckula-AU** [comment]
Yes, all the GPUCRASH files are from before I disabled r_interpolate_model_animation + r_interpolate_model_transform.
I have not had another crash since adding the 2 lines to the config.

Played another hour or so with interpolation disabled, no crashes.

**Comment by ShroomKing** [comment]
just wanted to point out that the gpucrashes only seem to occur in the campaign(id1).

since you switched to GL renderer i haven't been playing the campaign, only mods and the missionpacks. and the crash has not happened, not even a single time(played through both missionpacks + dimensions of the past(dopa mission pack) and abyss of pandemonium(aopfm_v2).  after i saw this issue, i decided to play through the campaign a second time, and it crashes after just a couple minutes of playing.

Also i just tried the latest commit, and i'm not sure why but the crashes seem to be gone. (played through episode 1 of the campaign on normal difficulty. 

Frame Interpolation was enabled the whole time

**Comment by Count-Duckula-AU** [comment]
Just tested v2.8 with animation interpolation enabled, the crash still happens at the same point for me. I'll disable it in the config and keep playing :)

**Comment by Phoenix09** [comment]
I'm consistently crashing it with interpolation disabled

[psp2core-1520378859-GPUCRASH.zip](https://github.com/Rinnegatamante/vitaQuake/files/1787159/psp2core-1520378859-GPUCRASH.zip)
